### ISSUE TITLE
Product Security

### ISSUE THREAD

**Issue by DaEpicR** [Vencord/Installer#104]
Please set up a **security policy** so we can report Vulnerabilities .

**Comment by mantikafasi** [comment]
everyday I wonder what kind of vulnerabilities you can find in a simple installer

**Comment by DaEpicR** [comment]
> everyday I wonder what kind of vulnerabilities you can find in a simple installer

well i will report one .

**Comment by Vendicated** [comment]
either join our Discord server and use modmail, or email vendicated@riseup.net. you may use https://vendicated.dev/pgp_key.asc.txt for signing your email

**Comment by DaEpicR** [comment]
> either join our Discord server and use modmail, or email [vendicated@riseup.net](mailto:vendicated@riseup.net). you may use https://vendicated.dev/pgp_key.asc.txt for encrypting your email

Done .
