### ISSUE TITLE
 Command-line injection vulnerability inside the Cli installer

### ISSUE THREAD

**Issue by DaEpicR** [Vencord/Installer#105]
# Code Vulnerability Report

### Executive Summary

This vulnerability report aims to address a critical security concern identified within the Vencord Installer codebase. The vulnerability pertains to the potential for command-line injection, which could allow malicious actors to execute arbitrary commands on the system where the application is running.

#### Vulnerability Description

The Vencord Installer codebase allows for user input from command-line arguments, specifically the `locationFlag` and `branchFlag`, without proper validation or sanitization. This lack of input validation exposes the application to the risk of command-line injection attacks.

#### Affected Components

The vulnerability affects the entire application, as it involves user input provided through command-line arguments.

#### Vulnerability Impact

The potential impact of this vulnerability includes:

1. Unauthorized execution of arbitrary commands.
2. Data corruption or deletion.
3. Unauthorized access to the system.
4. System compromise and data breaches.

### Vulnerability Mitigation

To address this vulnerability, the following steps should be taken:

1. **Implement Input Validation**: Replace direct usage of command-line arguments with the `flag` package for parsing and validating user inputs. The `flag` package provides built-in input validation and parsing features, making it a more secure choice.

2. **Validate User Inputs**: After parsing the flags, add explicit validation to ensure that user inputs are safe and expected. For example, validate the `branchFlag` to ensure it matches predefined values.

3. **Sanitize Input Parameters**: When calling functions that use user input, pass the validated and sanitized input parameters to reduce the risk of command injection vulnerabilities.

4. **Handle Errors Robustly**: Improve error handling throughout the codebase to provide better feedback to the user and ensure that errors do not lead to unexpected program behavior.

### Recommendations

1. The development team should immediately address this vulnerability by implementing the suggested mitigation steps.
2. The code should be reviewed for other potential security vulnerabilities, and a comprehensive security review should be conducted to identify and remediate any further issues.
3. The development team should establish security best practices and integrate them into the development process to prevent future vulnerabilities.

**Comment by ImLvna** [comment]
stop. we already said the issue was invalid. dont reopen it

**Comment by TheKodeToad** [comment]
:moyai:

**Comment by mantikafasi** [comment]
please hack me using that vulnerability
