### ISSUE TITLE
Openasar Integration 

### ISSUE THREAD

**Issue by Vendicated** [Vencord/Installer#11]
A lot of people seem to struggle installing OpenAsar alongside Vencord. Integrating it into the installer would be trivial and probably useful for a bunch of people

I'm not sure what the best way to incorporate this into the ui would be, a dedicated button would feel weird. In any case, there should be a way to unpatch it again and it should show a clear disclaimer that it's third party software not affiliated with us that they're installing at their own discretion

**Comment by lemon07r** [comment]
I think a checkbox in the installer would be sufficient. It would be fine if Openasar settings could be accessed the way it normally it is after install.

**Comment by Vendicated** [comment]
Added in VencordInstaller v1.2.3
