### ISSUE TITLE
Request: Make support for discord-ptb-portable

### ISSUE THREAD

**Issue by Cbert** [Vencord/Installer#111]
Is there a way to install Vencord on discord-ptb-portable?
https://github.com/portapps/discord-ptb-portable/releases

**Comment by ImLvna** [comment]
just manually enter the path to the folder containing discordptb.exe

**Comment by Cbert** [comment]
![image](https://github.com/Vencord/Installer/assets/9320867/5ed26f9f-5e60-4202-9ca8-4011f3160f19)
![image](https://github.com/Vencord/Installer/assets/9320867/18f29c8d-2c6d-4375-a1b1-1aecba0058f1)
does not work
```
Invalid Location
The specified location is not a valid Discord install. Make sure you select the base folder.
```

**Comment by Cbert** [comment]
![image](https://github.com/Vencord/Installer/assets/9320867/509daf0c-cba2-426a-bf82-03e3d415ae00)
![image](https://github.com/Vencord/Installer/assets/9320867/3fa07a0a-4299-4f20-88e2-37c25a59ddcf)
does not work
```
Invalid Location
The specified location is not a valid Discord install. Make sure you select the base folder.
```

**Comment by ImLvna** [comment]
try going back a few folders, to discord-ptb-portable-xxxxxx

**Comment by Cbert** [comment]
![image](https://github.com/Vencord/Installer/assets/9320867/d37bae2b-5524-484b-9a57-db88a0f826d0)
same result or failure

**Comment by urmomstoaster** [comment]
![image](https://github.com/Vencord/Installer/assets/116987903/7a24926e-3feb-4456-89c0-e00f26201858)
reproduced with Portapps Discord (stable).

**Comment by Vendicated** [comment]
because their folder structure is different than official discord

feel free to open a pr to add support for it, or just use [Vesktop](https://github.com/Vencord/Vesktop) portable

**Comment by urmomstoaster** [comment]
For now I'm using Vesktop and recommending that, but def will look into creating a PR, however given the faster speed of Vesktop there's not much point of creating a PR for it, better issues to focus on imo lol.

**Comment by Ryuu43** [comment]
I found a way to install it on Discord Portable via the Cli version

**Comment by StRonKEA** [comment]
> I found a way to install it on Discord Portable via the Cli version

Can you share the solution you found?

**Comment by Ryuu43** [comment]
I don't use it anymore but I used the cli and installed vencord in the Discord Portable folder and it
