### ISSUE TITLE
How to change the VENCORD_USER_DATA_DIR variable?

### ISSUE THREAD

**Issue by Boxersteavee** [Vencord/Installer#113]
I am trying to install vencord on ubuntu, I have discord installed using the .deb package from their website. I use 2 users on ubuntu, and when I try to access discord from the one that I didn't use when installing vencord (User B), it doesn't open, as the configuration files are stored in the home directory of User A. The installer shows the directory at the top, and says if I wish to change it, I need to change the VENCORD_USER_DATA_DIR variable, how do I do this? I have looked inside the .sh file, but I couldn't find it. Yes I have asked on the support discord, it was no use, i was just told that it shouldn't be changed unless i really need to change it, and they said if I do need to, that I should 'just google it'... _so much for a support server_... So here I am making a github issue.

**Comment by IThundxr** [comment]
Google it, it's a simple thing search "set environment variable Linux"
