### ISSUE TITLE
Repairing vencord uninstalls OpenAsar, clicking install OpenAsar does not fix it.

### ISSUE THREAD

**Issue by KraXen72** [Vencord/Installer#121]
I have Vencord installed through this installer.
If i go to OpenAsar releases and manually swap the app.asar file, it installs OpenAsar but removes Vencord.
If i then go to the installer and click Repair Vencord, it adds back Vencord but removes OpenAsar.
If i click Install OpenAsar, it does not install it and it's still just Vencord installed.

In the past it was easily possible to use both at the same time. Please, fix this issue and allow it again, either by fixing the Install OpenAsar button or by not removing it when Reparing Vencord

stable 266159 (04f86d0) Host 1.0.9033 x86 (43813) Windows 10 64-bit (10.0.19045)
vencord f1bdf38, installer version 6f8e7f7

**Comment by Vendicated** [comment]
don't use the openasar installer, it's not supported. the install openasar option works just fine. if it doesn't, something is messed up (likely due to mixing both installers), reinstall Discord

**Comment by KraXen72** [comment]
what openasar installer are you thinking of? the .bat one? i am not using that.  i'll try deleting all app.asar thing from %localappdata% and just copying in an app.asar from openasar releases, and will report back.

**Comment by KraXen72** [comment]
okay, it works now - there was some sort of a _app.asar file, likely due to me using the bat installer some time ago. deleting that and pasting in the latest app.asar from openasar's releases worked. Might be useful to try to delete any _app.asar files when clicking the Install OpenAsar button, but this works fine.

**Comment by KraXen72** [comment]
in OpenAsar's wiki, the install instructions recommend pasting in the file manually, that's why i did it. I didn't know if Vencord's install Openasar button requires the original app.asar from discrod to be there. Anyway, it works now, thanks!

**Comment by DigitalNXZ** [comment]
> no. use the vencord installer for installing OpenAsar. do not mess with the files manually

hei, am I blind? I installed 'Vesktop' on Linux, couldn't find an OpenAsar Installation in the installer neither the Discord settings, where could I find it if it is supported in 'Vesktop' (dis even a official build?) :,)

**Comment by nin0-dev** [comment]
> > no. use the vencord installer for installing OpenAsar. do not mess with the files manually
> 
> hei, am I blind? I installed 'Vesktop' on Linux, couldn't find an OpenAsar Installation in the installer neither the Discord settings, where could I find it if it is supported in 'Vesktop' (dis even a official build?) :,)

yes, vesktop is official. no, openasar isn't supported on vesktop. it's discord desktop only

**Comment by DigitalNXZ** [comment]
aww sad :(

> it's discord desktop only
didn't quite understood this, so how would I get the Vencord client with the OpenAsar option in it?

if I would interpret it right, I would need to install the 'default' Discord and doin' the steps provided in the README?

Whats the benefit of Vesktop against Discord  x Vencord? beside that Vesktop seems much more easy to install and has 'Venmic'? - I'm on Wayland KDE if it is imporant to know.

**Comment by Sqaaakoi** [comment]
> I'm on Wayland

Vesktop has working screenshare as it is a web client with regular Electron (+ Venmic for audio) instead of stripped down Electron + propietary Xorg only screensharing native module
