### ISSUE TITLE
MacOs Ventura 13.6.4 Crash

### ISSUE THREAD

**Issue by HugoMskn** [Vencord/Installer#122]
Hey

Tried to install vencord on my patched iMac with Ventura 13.6.4 installed but for some reason after patching discord crash on launch, tried with open asar, still crash, if i unpatch it works fines (discord, not vencord)

When running discord from terminal with sudo i just get zsh: trace trap  sudo ./Discord when it crash 

Any idea ?

**Comment by Vendicated** [comment]
use our support channel

**Comment by Vendicated** [comment]
also seems like an issue with your system so likely nothing we can do
