### ISSUE TITLE
Installing Vencord breaks discord_arch_electron

### ISSUE THREAD

**Issue by GalecO1987** [Vencord/Installer#125]
After the new update to discord_arch_electron (updated electron?) Discord with installed Vencord doesn't work. Processes show up in Task Manager, but nothing happens. Running Discord from the terminal gives error. Before the update to 0.0.45 everything worked perfectly.

stable 274388 (865dbf6) Host 0.0.45 x64 Linux 64-bit (6.7.9-arch1-1) EndeavourOS
![vencord installer](https://github.com/Vencord/Installer/assets/78051261/a4d3219d-069b-43b1-aecb-12a2b0b5b74b)

**Comment by Vendicated** [comment]
require.main is undefined, which means discord is being run in some very weird way

nothing we can fix

**Comment by Vendicated** [comment]
i recommend against using these packages nowadays. they are hardly useful anymore considering discord no longer uses a super ancient electron version. just use normal discord, or if you want latest electron, use vesktop
