### ISSUE TITLE
MacOS: try to find Discord.app in local Applications folder as well

### ISSUE THREAD

**Issue by jannisbecker** [Vencord/Installer#126]
Currently, the installer on MacOS only seems to try to find the Discord folder in the system-wide applications folder /Applications.
However, MacOS supports creating local applications folders per user, in ~/Applications (i.e. /Users/<username>/Applications).

Right now I have to manually type that path as a custom install location every time, it'd be nice it was automatically searched as well.

**Comment by Vendicated** [comment]
done via https://github.com/Vencord/Installer/pull/124
