### ISSUE TITLE
Microsoft Defender: Trojan:Win32/Znyonm VencordInstallerCli.exe

### ISSUE THREAD

**Issue by sagexfors** [Vencord/Installer#127]
It's getting flagged

**Comment by Vendicated** [comment]
false positive. ignore it, unquarantine/whitelist the binary

there's nothing we can do. report it as false positive to microsoft if you care

**Comment by bb010g** [comment]
On VirusTotal: <https://www.virustotal.com/gui/file/466d2a0be1f380ddffed052df3cc132125fa34dc1af29312e14f13f358c8d2a2>

Defender isn't the only thing flagging this, but I have also never heard of the other two AV solutions (Jiangmin & BitDefenderTheta) that are detecting.

**Comment by MrDiamondDog** [comment]
> On VirusTotal: https://www.virustotal.com/gui/file/466d2a0be1f380ddffed052df3cc132125fa34dc1af29312e14f13f358c8d2a2
> 
> Defender isn't the only thing flagging this, but I have also never heard of the other two AV solutions (Jiangmin & BitDefenderTheta) that are detecting.
> 
> EDIT: Also reported as a false positive to Microsoft, submission ID 3fe767c7-aedc-403e-b842-48212228c949.

Still false positives. Just ignore them

**Comment by sagexfors** [comment]
it's no longer flagged by defender @bb010g thanks for reporting
