### ISSUE TITLE
Installer not detecting the VENCORD_USER_DATA_DIR variable

### ISSUE THREAD

**Issue by ljcool2006** [Vencord/Installer#129]
1. Add the "VENCORD_USER_DATA_DIR" environment variable
2. Open the installer

Expected result:
The file path after "Files will be downloaded to:" would show the chosen custom location

Actual result:
It shows the default location

Operating system: Windows 10 22H2 build 19045.4291

**Comment by Vendicated** [comment]
then you did it wrong. make sure you re-login after adding new variables to properly apply them

we don't actually support this option, it's just provided for advanced users who know what they're doing
