### ISSUE TITLE
can't install due to older bd installation?

### ISSUE THREAD

**Issue by fluffyloopy** [Vencord/Installer#13]
the installer chooses older directory which has an installation of discord bd which didn't go away upon using the bd installer to uninstall.
![image](https://user-images.githubusercontent.com/36381994/214204254-fa6e8f7b-d2cb-40ec-8288-70215a10d92a.png)
![image](https://user-images.githubusercontent.com/36381994/214204299-6a9123d4-0953-4911-883c-6d7f56d72469.png)
would this be an issue of bd?

**Comment by Vendicated** [comment]
just delete the folder it mentions manually

**Comment by fluffyloopy** [comment]
yeah, deleting that folder, reopening discord and then trying fixed it.
