### ISSUE TITLE
sorry which one do i install? im on PC..

### ISSUE THREAD

**Issue by St1nGxD** [Vencord/Installer#14]

**Comment by Vendicated** [comment]
what

**Comment by St1nGxD** [comment]
not even kidding i literally don't know......

**Comment by Vendicated** [comment]
okay I have no idea what you're asking, please read the README and if you can't figure it out join our support server

**Comment by St1nGxD** [comment]
i should've clarified which "release" but alright

**Comment by ArjixWasTaken** [comment]
![image](https://user-images.githubusercontent.com/53124886/216761666-6cd746e8-e87a-4fb5-ac7d-00263c2f67ef.png)

**VencordInstaller.exe**
![image](https://user-images.githubusercontent.com/53124886/216761687-6bb00e0c-3721-424e-b495-0476124a325b.png)

**Comment by St1nGxD** [comment]
whats the danger of running the installer as Admin?

**Comment by MeguminSama** [comment]
It messes with the permissions of the files. There is no reason to need to run it as admin.

**Comment by ArjixWasTaken** [comment]
Giving admin rights to a program that is not designed to work with admin rights could lead to the loss of important files.

For example when running `cmd` as admin the current directory is usually `C:/Windows/System32` (for whatever fucked up reason microsoft decided to do that), running programs with that as the current directory is dangerous and reckless.
In this case that isn't an issue, but you should never mess with system files.

Also, the installer downloads some files off github, those files would be owned by the admin user (in case that is a different user than your user), those files being owned by an admin would mean you need admin rights to open/edit them.

That would lead to permission issues as megumin said.

**Comment by somerandomcloud** [comment]
but why can you run linux installer with root..? :thinking: 

Checkmate liberals
