### ISSUE TITLE
Feature request: Unelevated mode for certain linux installs

### ISSUE THREAD

**Issue by november781** [Vencord/Installer#145]
Currently the vencord installer script for Linux runs the downloaded patcher binary as root 100% of the time. There is definitely one specific case where that is undesirable. 

When installing Discord manually using the tar.gz file, discord can be placed into the users ~/.local/share/ directory and be installed and run while all files are owned by the installing user. In this situation, running the vencord patcher as root changes the ownership of app.asar which is undesirable as it breaks several functions in discord itself. Personal testing shows that elevated permissions are not required to patch the asar file under this install process.

This case is likely to not affect most users but for the few of us who manage discord through means other than our system package manager or flatpak it would be a major improvement.

**Comment by Vendicated** [comment]
the installer does not actually need root in any way, it's just that the shell script you `curl` and `sh` runs it as root. if you want to run as non root, simply download the binary manually (or look at the shell script and modify it to run without root)
