### ISSUE TITLE
[Linux] Can't install

### ISSUE THREAD

**Issue by CrossyAtom46** [Vencord/Installer#24]
![image](https://user-images.githubusercontent.com/82151617/226402557-dc39af18-d304-4a9c-9486-fdc2e56a2912.png)
^C^Xutkug@UBUNTU-E17DEO:~$ sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"
Downloading Installer...
X11 detected

Now running VencordInstaller
Do you want to run as root? [Y|n]
This is necessary if Discord is in a root owned location like /usr/share or /opt
> n
Running unprivileged
Using UserConfig
Checking if /home/utkug/.config/Vencord/dist exists: Yes
Is Dev Install:  false
Fetching https://api.github.com/repos/Vendicated/Vencord/releases/latest
Checking for Installer Updates...
Fetching https://api.github.com/repos/Vencord/Installer/releases/latest
Finished fetching GitHub Data
Latest hash is e36f4e5 Local Install is outdated!
Checking if resources exists: No
Checking if app.asar exists: No
Tried to parse invalid Location: 
Checking if /snap/bin/discord/resources exists: No
Checking if /snap/bin/discord/app.asar exists: No
Tried to parse invalid Location: /snap/bin/discord

**Comment by Vendicated** [comment]
snap isn't supported, download the .deb file from discords official download page

**Comment by CrossyAtom46** [comment]
ok i didnt know that. i thought discord still doesnt supports linux officially
