### ISSUE TITLE
welp

### ISSUE THREAD

**Issue by Bruhman69420XD** [Vencord/Installer#27]
![image](https://user-images.githubusercontent.com/94253413/226417414-da5bb483-2732-4fc7-9099-3a70b851c0bd.png)

**Comment by lewisakura** [comment]
Close Discord fully before trying to patch. It's probably still running in the background.

**Comment by Bruhman69420XD** [comment]
how to close discord fully

**Comment by lewisakura** [comment]
Alt+F4 or go to the tray in the bottom right and close it from there. Alternatively, Task Manager.

**Comment by Bruhman69420XD** [comment]
ok

**Comment by Bruhman69420XD** [comment]
should I click end task?

**Comment by lewisakura** [comment]
Yes.

**Comment by Bruhman69420XD** [comment]
ok
