### ISSUE TITLE
Lightcord support

### ISSUE THREAD

**Issue by BlackusPL** [Vencord/Installer#30]
Please add Lightcord support or if is there any way to install it please tell me

**Comment by lewisakura** [comment]
Vencord cannot be installed with other clients.

**Comment by ArjixWasTaken** [comment]
> Vencord cannot be installed with other clients.

Lies.

Vencord can be installed with other clients, such an example is ArmCord.

**Comment by MeguminSama** [comment]
Lightcord is abandonware that hasn't been updated in two years. We won't work to officially support this.
