### ISSUE TITLE
addition switches for cli installer

### ISSUE THREAD

**Issue by solomoncyj** [Vencord/Installer#33]
additioal switches 

1.  ```-dir <dir>``` : installs vencord to <dir>
2.  ```-dir [default|stable|ptb|canary]``` : installs vencord to the location sepecifed. defult location is the first hit

**Comment by Vendicated** [comment]
what's the purpose of this? you can already choose which one you want

**Comment by solomoncyj** [comment]
> what's the purpose of this? you can already choose which one you want

i want to slient install it

**Comment by Vendicated** [comment]
you would just need to edit https://github.com/Vencord/Installer/blob/main/cli.go#L17

**Comment by apprehensions** [comment]
https://pkg.go.dev/flag
