### ISSUE TITLE
Cant change theme anymore

### ISSUE THREAD

**Issue by kaidooo7** [Vencord/Installer#36]
Was working fine perfectly untill I used spoticord theme then i couldnt change it anymore. Might just re-install but hope to get this fixed so it doesnt happen again.
![image](https://user-images.githubusercontent.com/126785109/226967648-cba97eb3-adb7-495d-b398-c1fbeeb4ee45.png)

**Comment by Vendicated** [comment]
wrong repo + use our support channel please
