### ISSUE TITLE
Completely incompatible with my laptop,

### ISSUE THREAD

**Issue by n3onwarrior56** [Vencord/Installer#42]
I'm running win 10 and the proper one doesn't work, terminal in any way doesn't work and making my own doesn't tell me shit how to do it and that's kinda out of my reach.
Please help.

**Comment by Vendicated** [comment]
use our support channel

**Comment by n3onwarrior56** [comment]
Where.

**Comment by somerandomcloud** [comment]
https://discord.gg/vencord
