### ISSUE TITLE
Not an issue but more of a question on how to uninstall the "nsis-installer.exe".

### ISSUE THREAD

**Issue by HiryuCV6** [Vencord/Installer#44]
![image](https://user-images.githubusercontent.com/113156159/227914444-7d172d84-8d31-40ae-b745-bf8a433c5011.png)

How would I uninstall this? (The "nsis-installer.exe")

**Comment by HiryuCV6** [comment]
Indeed. I just thought that it was the very first link that has to be downloaded and installed as it mostly is. Thank you for answering.

**Comment by lewisakura** [comment]
If you really need to, it's in your local appdata folder. You can install it from there.

**Comment by HiryuCV6** [comment]
> If you really need to, it's in your local appdata folder. You can uninstall it from there.

To clarify, I can uninstall/remove the files and/or folders installed by "nsis-installer.exe" from the AppData Local folder? If so, could you please provide the specific file and folder names that were installed by the installer? This will help me give you more accurate instructions on which files and folders to delete from the AppData Local folder. Appreciate the reply.

**Comment by lewisakura** [comment]
![image](https://user-images.githubusercontent.com/8019327/227968923-ecd568b5-4eb6-4349-99e4-d6514792833c.png)
`%localappdata%/vencordpatcher/uninstall.exe`

**Comment by HiryuCV6** [comment]
> ![image](https://user-images.githubusercontent.com/8019327/227968923-ecd568b5-4eb6-4349-99e4-d6514792833c.png) `%localappdata%/vencordpatcher/uninstall.exe`

Oh, was referring about the nsis-installer.exe if it could be uninstalled. But I appreciate the reply.

**Comment by lewisakura** [comment]
That is what the NSIS installer installs. Run `uninstall.exe` from that folder and it will clean it up for you.

**Comment by HiryuCV6** [comment]
> %localappdata%/vencordpatcher/uninstall.exe

Woah really? Sorry I misunderstood that, since I saw the vencordinstaller which I can uninstall the vencord if I ran it. Appreciate the help so much! Thank you!
