### ISSUE TITLE
cant launch discord anymore

### ISSUE THREAD

**Issue by ihaveaskimask** [Vencord/Installer#49]
ive updated vencord and used the update feature of the installer but launching discord it gets stuck with "downloading updates 1 of 15" and then "update failed" on a loop
![image](https://user-images.githubusercontent.com/95984298/230980648-67516e61-07f3-469c-ae43-66fe259588e5.png)
![image](https://user-images.githubusercontent.com/95984298/230980713-5ef59db0-0a16-4248-ab2b-589890f553cd.png)

**Comment by Vendicated** [comment]
use our support channel please

**Comment by ihaveaskimask** [comment]
ok sorry

**Comment by ihaveaskimask** [comment]
sorry, wheres the support channel?
