### ISSUE TITLE
Preserve environment variables

### ISSUE THREAD

**Issue by Microeinstein** [Vencord/Installer#51]
Please preserve user's environment variables with `sudo -E` ([here](https://github.com/Vencord/Installer/blob/main/install.sh#L43)).

I personally need this to pass `LIBGL_ALWAYS_SOFTWARE=1`...

(Yes, the installer is hardware accelerated and I'm stuck to OpenGL 2.1)

---

My current workaround
```sh
url="https://github.com/Vendicated/VencordInstaller/releases/latest/download/VencordInstaller-x11"
out="vinst"
curl -sS "$url" --output "$out" --location
chmod +x "$out"
LIBGL_ALWAYS_SOFTWARE=1 sudo -E "$out"
```

**Comment by Vendicated** [comment]
I don't want to do this since preserving environment variables is terrible for security. You should instead fix your sudoers file to always keep this environment variable https://wiki.archlinux.org/title/Sudo#Environment_variables
