### ISSUE TITLE
make it so that if you uninstall vencord, the css shit resets and deletes everything on it. my discord fully breaks with vencord is installed because some imbecile cant code for shit and his code fully broke my discord

### ISSUE THREAD

**Issue by pancakes111213123432453254235** [Vencord/Installer#53]

**Comment by Vendicated** [comment]
open the dev tools with `CTRL + Shift + i` and click on the "console" tab at the top. Then paste and run (with enter) the following code.

It will
- disable custom css (you can turn it back on in Vencord Settings)
- copy your current theme links to your clipboard as a backup
- remove all themes

```js
(() => {
    Vencord.Settings.useQuickCss = false
    copy(Vencord.Settings.themeLinks.join("\n"))
    Vencord.Settings.themeLinks = []
})()
```
