### ISSUE TITLE
[Feature request] discord-screenaudio support/integration?

### ISSUE THREAD

**Issue by lolwhat-codesucc** [Vencord/Installer#54]
So, i was using [discord-screenaudio](https://github.com/maltejur/discord-screenaudio) (i'm using Arch btw) for a while now, and it is very convenient since standart discord client can't even stream sound out-of-the-box, and i, unlike many linux users, am too lazy to fix this issue myself.
Vencord has some very cool plugins, but it seems that the installer cannot install it on a discord-screenaudio client. Will there be any way to fix this, or, perhaps, a similar feature?

**Comment by Vendicated** [comment]
out of scope, but discord-screenaudio are working on this themselves
