### ISSUE TITLE
Android integration support appeal.

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [Vencord/Installer#55]
Can this code be modded and compiled for Android device so that Android devices can use more plugins just like old Aliucord in the new updated versions of Discord. Discord is updated their app to react native so the old Aliucord is broken so it can get any new updates and features by Discord. Aliucord is based on old method of modding and they have for a lot years so much cool and best plugins in the world that is ported from BetterDiscord but after this freaking Discord update, this adventure is officially EOL so every single plugin by devs needs to be written from scratch for react native platform. Many devs just quit in porting from desktop PCs those cool plugins and some of them are died so we can't get many plugins anymore i  those new versions of Discord.

This project can be light for us and revival for our devices to be able to mod Discord again like before because this Discord client have already PC support and many plugins that we've used before in old Aliucord client but in react-native plugins list, those plugins are not ported and many of them will never be ported so it would be nice for android devices to get support, even unofficialy to run this client and have again traditional number of plugins to continue to use those cool experience with those plugins.

I know that PCs are much in trending than phones/tablets but let's accept the truth - many people use more phones than PC due to many reasons - and most of them is money inability to get some PC but also there is other reasons too so it's actually the fact that phone is much better than PC in the terms of having it in 2023 and to be able without any lags to use it online for literally anything.

Especially, rooted Android devices. So, one Discord client who have at least very similar number or completely the same number of plugins like PC clients have it will be so much useful and the best. So, even if maybe many of them are even don't care at least a little bit for mobile users, it would be nice to do this - one good will for us sadly poor-in-development-popularity mobile users to get experience we had before in the history of Discord clients for Android.

Thank you so much in advance devs and owner for your understanding and will to do this.

**Comment by Vendicated** [comment]
you can use https://github.com/Vencord/Android, other than that, not possible

**Comment by ArjixWasTaken** [comment]
(please don't use vencord for android, it is a horrible experience, use vendetta instead :pray:)

**Comment by ArjixWasTaken** [comment]
You should instead go complain to aliucord for not porting over the plugins you liked lol.

(vendetta is better btw)

**Comment by admin-elvistrujanovic** [comment]
> You should instead go complain to aliucord for not porting over the plugins you liked lol.
> 
> (vendetta is better btw)

They don't have plugins I used before in old Aliucord so I can't use that client. BetterDiscord for example have everything, but they hates mobile phones so they don't want to integrate their project to android even if they can so I need to use those plugins that is going to never be ported to React-Native
