### ISSUE TITLE
No compability for 32 Bits

### ISSUE THREAD

**Issue by YASUEMMNNMM** [Vencord/Installer#58]

**Comment by Vendicated** [comment]
use the cli

**Comment by Redundakitties** [comment]
https://github.com/Vencord/Installer/releases/download/v1.2.8/VencordInstallerCli.exe

**Comment by YASUEMMNNMM** [comment]
Hello, I just clicked on the link, and downloaded the file and did not
work. I tried the Powershell thing still did not work I got this error on
Powershell

**Comment by YASUEMMNNMM** [comment]
Hello, The CLI Version did not work, I tried the Powershell one, but I got
this error. Please Reply to me and help me with this problem. Thank You :).
[image: image.png]
