### ISSUE TITLE
i have no idea whats happening 

### ISSUE THREAD

**Issue by authenyo** [Vencord/Installer#60]
im a complete noob, i run the command on my terminal like it said on the readme

then this happens

``Downloading Installer...
X11 detected

Now running VencordInstaller
Do you want to run as root? [Y|n]
This is necessary if Discord is in a root owned location like /usr/share or /opt
> y
Running with sudo
[sudo] password for levih:          
VencordInstaller was run with root privileges, actual user is levih
Looking up HOME of levih
Actual HOME is /home/levih
Using UserConfig
Checking if /home/levih/.config/Vencord/dist exists: Yes
Is Dev Install:  false
Fetching https://api.github.com/repos/Vendicated/Vencord/releases/latest
Checking if /usr/share/discord/resources exists: Yes
Checking if /usr/share/discord/resources/app exists: No
Checking if /usr/share/discord/resources/app.asar is directory: No
Found Discord install at  /usr/share/discord
Checking for Installer Updates...
Fetching https://api.github.com/repos/Vencord/Installer/releases/latest
panic: failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

goroutine 1 [running, locked to thread]:
github.com/AllenDang/giu.NewMasterWindow({0xa44174, 0x11}, 0x4b0, 0x320, 0x40?)
	/home/runner/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:68 +0x41f
main.main()
	/home/runner/work/Installer/Installer/gui.go:64 +0x98``

i dont know what steps i have to follow how do i fix this when i open discord nothing happens help

**Comment by Vendicated** [comment]
Install mesa / use the CLI that you can find in releases. Please use our support channel if you need more help
