### ISSUE TITLE
how do you create a a powershell cli/gui install command with a fork of vencord

### ISSUE THREAD

**Issue by Pickymarker** [Vencord/Installer#64]
how do you create a a powershell cli/gui install command with a fork of vencord

**Comment by Vendicated** [comment]
there is no good way to do that. you have to fork the repo and change the urls

**Comment by Pickymarker** [comment]
what urls do i have to change because i want to be able to have it still work for people that can't run the gui and also people that can at the same time

**Comment by Pickymarker** [comment]
i just need to know what urls to change thats it

**Comment by Pickymarker** [comment]
i did not spam you said you have to fork the repo and change the urls and then just didn't answer how unless you add easy plugin install to vencord then you should have a guide or something telling people how to install a vencord fork as cli no gui

**Comment by Vendicated** [comment]
https://github.com/search?q=repo%3AVencord%2FInstaller%20https&type=code
