### ISSUE TITLE
Vencord cant patch even when im using the 2nd option

### ISSUE THREAD

**Issue by notkxyla** [Vencord/Installer#74]
It shows this error in the pic and it wont patch the discord files. I thought it downloaded the file but when going to folder path it doesnt show vencordinstaller.exe file, it didnt download. How to fix this? 
![RHCRBEGY](https://github.com/Vencord/Installer/assets/136187924/d83e94bf-0aa9-478c-ae65-9c5c67f3a38f)

**Comment by ArjixWasTaken** [comment]
😮

**Comment by h4rldev** [comment]
I can barely take this entire screenshot seriously

**Comment by Vendicated** [comment]
use our support channel please
