### ISSUE TITLE
Curl command for linux not showing installation prompts.

### ISSUE THREAD

**Issue by SidonTheTroll** [Vencord/Installer#77]
The installation command for linux, i.e., __sudo sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)__ doesn't show installation prompts in Linux systems. Issue might look like a bug but removing flags doesn't work.

## Ways to replicate
- Copy installation command for Linux from https://github.com/Vencord/Installer 
- Paste in terminal and hit enter 
- If the process goes right (in creating the issue ofc), it will show this output 
![Terminal Output](https://media.discordapp.net/attachments/876696663060774942/1128521262063427664/image.png)

## My way of solving it 
- Go to the curl redirect page.
- Copy the script. 
- Create a .sh file and paste the code [like this](https://github.com/Vencord/Installer/assets/70560640/1e65fb35-f629-4789-99ee-4b536bb85bf8).
- Execute the file.
If everything works and GNU/Linux gods are happy, it will install Vencord flawlessly

**Comment by Vendicated** [comment]
you are missing a quote at the end of your command

**Comment by SidonTheTroll** [comment]
Oop :skull:
