### ISSUE TITLE
Installer not detecting DC Installation on Ubuntu

### ISSUE THREAD

**Issue by felix25364** [Vencord/Installer#79]
The Vencord Installer doen't auto detect or manually detect my Discord Installation on Ubuntu 22.04LTS!
In terminal it says:
Checking if /snap/bin/discord/resources exists: No
Checking if /snap/bin/discord/app.asar exists: No
Tried to parse invalid Location: /snap/bin/discord

I tried snap/bin/ as folder and /snap/ but nothing seem's to work

**Comment by ItzOnlyAnimal** [comment]
snap is not supported
