### ISSUE TITLE
Qustion

### ISSUE THREAD

**Issue by B0tCreati0n** [Vencord/Installer#86]
In the github installer it does state that i should not run as admin, what will happen if i run it as admin?

**Comment by B0tCreati0n** [comment]
https://github.com/Vencord/Installer#windows

**Comment by Vendicated** [comment]
your house will get raided by 17 IDF soldiers

**Comment by Vendicated** [comment]
On a more serious note though, not much will happen. It's probably fine. But it might mess up permissions and environment variables which could mess with Vencord's updater

**Comment by B0tCreati0n** [comment]
Thank you
