### ISSUE TITLE
download fails on linux parrot os

### ISSUE THREAD

**Issue by nik-bik** [Vencord/Installer#89]
i tried installing it but i get this can somebody help me 

i get this:
Actual HOME is /home/nik
Using UserConfig
Checking if /home/nik/.config/Vencord/dist exists: Yes
Is Dev Install:  false
Fetching https://api.github.com/repos/Vendicated/Vencord/releases/latest
Checking if /usr/share/discord/resources exists: Yes
Checking if /usr/share/discord/resources/app exists: No
Checking if /usr/share/discord/resources/app.asar is directory: No
Found Discord install at  /usr/share/discord
Checking if /opt/Discord/resources exists: Yes
Checking if /opt/Discord/resources/app exists: No
Checking if /opt/Discord/resources/app.asar is directory: No
Found Discord install at  /opt/Discord
Checking for Installer Updates...
Fetching https://api.github.com/repos/Vencord/Installer/releases/latest
Finished fetching GitHub Data
Latest hash is 1a62249 Local Install is outdated!
panic: failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

goroutine 1 [running, locked to thread]:
github.com/AllenDang/giu.NewMasterWindow({0xa4528d, 0x11}, 0x4b0, 0x320, 0x40?)
	/home/runner/go/pkg/mod/github.com/!allen!dang/giu@v0.6.2/MasterWindow.go:68 +0x41f
main.main()
	/home/runner/work/Installer/Installer/gui.go:70 +0x98

**Comment by Vendicated** [comment]
you have no opengl support. install mesa or use the cli
