### ISSUE TITLE
Anyone else getting this issue? or do I need to reinstall discord?

### ISSUE THREAD

**Issue by PinkDucki** [Vencord/Installer#92]
I went to message someone, then discord asked me if I was a bot, and I was unable to send the message (this may be unrelated, but I'm not sure, it just happened to happen right before this,). So I restarted discord, and then not a single message in any DM, server channel, etc. would load. So I opened the vencord installer, and pressed reinstall/repair, and the installer froze and went into 'Not Responding'. I tried restarting discord and the installer a couple more times, and reintalling the vencord installer, but the same thing happened. So I just pressed uninstall vencord, and then reinstalled it, but when I opened discord, vencord wasn't patched in. Not sure if this is a vencord issue or if its something else.

**Comment by Vendicated** [comment]
use our support channel
