### ISSUE TITLE
[BUG] Font not rendered properly. Installer Interface not readable

### ISSUE THREAD

**Issue by michihupf** [Vencord/Installer#96]
I have provided an image. I am also getting the log message: "Latest hash is c752be4 Local Install is outdated!" if that helps. I actually have no idea what could cause this.

![image](https://github.com/Vencord/Installer/assets/26794144/5da4e4a3-c3ef-42bc-9156-1d1c64a16893)

Additional info:
OS: Arch Linux
Kernel: linux 6.4.12.arch1-1
Display Server: xorg-server 21.1.8-2 (xorg)
Window Manager: awesome 4.3-3

GPU: Nvidia GeForce GX TITAN X

Any hints would be helpful. As a side note, [vencord-installer-bin](https://aur.archlinux.org/packages/vencord-installer-bin) leads to the same issue

**Comment by Vendicated** [comment]
try having a less scuffed system. install basic fonts
